version: '3.7'

services:
  nextcloud:
    build: .
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_ROOT}/config:/var/www/html/config
      - ${NEXTCLOUD_ROOT}/custom_apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_ROOT}/themes:/var/www/html/themes
      - ${NEXTCLOUD_ROOT}/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
      - redis
      - letsencrypt
      - proxy
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - proxy-tier
      - default

  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --max_allowed_packet=32505856
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
      # if you prefer using filesystem instead
      # - ${NEXTCLOUD_ROOT}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nextcloud-proxy
    networks:
      - proxy-tier
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PROXY_ROOT}/conf.d:/etc/nginx/conf.d:rw
      - ${PROXY_ROOT}/vhost.d:/etc/nginx/vhost.d:rw
      - ${PROXY_ROOT}/html:/usr/share/nginx/html:rw
      - ${PROXY_ROOT}/certs:/etc/nginx/certs:ro
      - ./config/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - proxy-tier
    volumes:
      - ${PROXY_ROOT}/certs:/etc/nginx/certs:rw
      - ${PROXY_ROOT}/vhost.d:/etc/nginx/vhost.d:rw
      - ${PROXY_ROOT}/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  nextcloud:
  mariadb:

networks:
  proxy-tier: