version: "3.7"

services:
  nextcloud:
    build: .
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_ROOT}/config:/var/www/html/config
      - ${NEXTCLOUD_ROOT}/custom_apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_ROOT}/themes:/var/www/html/themes
      - ${NEXTCLOUD_ROOT}/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
      - redis
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - TRUSTED_PROXIES=172.18.0.0/16
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${SUB_DOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=letsencrypt
      - traefik.http.routers.nextcloud.entrypoints=websecure
      #
      # make calDAV/cardDAV work
      - "traefik.http.middlewares.nextcloud_caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_caldav.redirectregex.regex=/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_caldav.redirectregex.replacement=/remote.php/dav/"
      #
      # "Strict-Transport-Security" HTTP header
      - "traefik.http.middlewares.nextcloud_headers.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nextcloud_headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud_headers.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN_NAME} *.${DOMAIN_NAME}"
      - "traefik.http.middlewares.nextcloud_headers.headers.stsIncludeSubdomains=true"
      #
      # declare middlewars
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_caldav@docker,nextcloud_headers@docker"
    networks:
      - web
      - internal

  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    restart: always
    command:
      - "--transaction-isolation=READ-COMMITTED"
      - "--binlog-format=ROW"
      - "--max_allowed_packet=32505856"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
      #
      # if you prefer using filesystem instead
      # - ${NEXTCLOUD_ROOT}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - internal

volumes:
  nextcloud:
  mariadb:

networks:
  web:
    external: true
  internal:
    external: false
